### ISSUE TITLE
.gallery takes up large portions on smaller screens (CSS)

### ISSUE THREAD

**Issue by WillStill** [spookybeetle/foundingOfPSB#1]
**Corresponding Commit:** [🐸](https://github.com/spookybeetle/foundingOfPSB/commit/474be4f16592612ff62669ece41a660cab232d38) _clicking the frog will send you to the commit_
The issue is described at the bottom of the page in a comment and preceded by "INPUT NEEDED"

The images on the side gallery don't change in width or height (and we want them to retain ratios) depending on screen width. The images dominate smaller screens. This leaves little space for the `.content` element and the children with the text. Two solutions would be to:

1. Move `.gallery` and its children to another location on the same page. e.g. Put the images below `.content` and all the text would show first. This would only apply to smaller screens, the page remains unchanged up until a certain screen width or
2. Scale the images. Image ratios _**should**_ remain the same and images will remain on the right of the screen. The images could scale much like the responsive design for `.content`, where it grows or shrinks into the room it is given.

More ideas are welcome. The purpose of this issue is to include others on any revisions that would change the original site's design, even if only slightly.

**Comment by JaxAbele** [comment]
I can see the issue. I don't think moving the gallery to a different location on the page would be a big deal. I'm all for whatever option is the easiest fix for the team.

**Comment by WillStill** [comment]
I'll implement something to scale the images to appropriate sizes for simplicity. This issue has been solved.
