### ISSUE TITLE
Branching Problem

### ISSUE THREAD

**Issue by ebeshero** [spookybeetle/foundingOfPSB#3]
@WillStill Your branch is out of date, and we need the team to be reviewing, understanding, and improving the XML code for the project. So, my recommendation is:

* Switch to main branch and `git pull`
* Switch to devBranch and run `git merge main`
* Then decide if you need to leave your branch running.

Most of your team doesn't really use branches and I'm not sure it's necessary for you to do this. A problem right now is that they are not literally seeing your work.

**Comment by ebeshero** [comment]
@WillStill Don't lose the work on your branch! You could just issue a pull request to merge it into main so the others will see your work.

**Comment by WillStill** [comment]
I've merged the branch into main. If we need another branch, its not too hard to make another one. 
The issue has been solved so I'm closing it.
